# Generated by Django 2.0 on 2019-01-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='humidity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reading',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reading',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reading',
            name='pressure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reading',
            name='temp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reading',
            name='wind_speed',
            field=models.CharField(max_length=50),
        ),
    ]
